steps:
  # 1. build immagine
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'gcr.io/adept-presence-464522-s3/celerya-dashboard',
      '.'
    ]

  # 2. push immagine
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/adept-presence-464522-s3/celerya-dashboard']

  # 3. deploy su Cloud Run (europe-west1)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'celerya-dashboard',
        '--image', 'gcr.io/adept-presence-464522-s3/celerya-dashboard',
        '--platform', 'managed',
        '--region', 'europe-west1',
        '--allow-unauthenticated'
      ]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - gcr.io/adept-presence-464522-s3/celerya-dashboard
